adminPassword: prom-operator

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts: ["grafana.btkv.tech"]
  path: "/"
  tls:
  - secretName: momo-main-cert
    hosts:
    - grafana.btkv.tech

persistence:
  type: pvc
  enabled: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    nginx-exporter:
      gnetId: 12708
      revision: 1
      datasource: Prometheus
    nginx-ingress:
      gnetId: 9614
      revision: 1
      datasource: Prometheus

