---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}