stages:
   - modules

variables:
   VERSION: 1.0.${CI_PIPELINE_ID}

frontend:
   stage: modules
   trigger:
      include:
         - local: "/.gitlab-ci/.frontend.yml"
      strategy: depend
   only:
      changes:
         - frontend/**/*

backend:
   stage: modules
   trigger:
      include:
         - local: "/.gitlab-ci/.backend.yml"
      strategy: depend
   only:
      changes:
         - backend/**/*
