---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "cluster-external-secret-app-lockbox"
spec:

  externalSecretName: "app-lockbox-es"

  namespaceSelector:
    matchLabels:
      momo-secret-app-lockbox: yc-auth-lockbox
  refreshTime: "1m"

  externalSecretSpec:
    secretStoreRef:
      name: cluster-secret-store-lockbox
      kind: ClusterSecretStore

    refreshInterval: "1h"

    target:
      name: momo-app-lockbox
      template:
        metadata:
          labels:
            argocd.argoproj.io/secret-type: repository
        # Use inline templates to construct your desired config file that contains your secret
        # no new lines at the end!!!
        data:
          type: git
          url: |-
            {{ .url | toString }}
          username: |-
            {{ .username | toString }}
          password: |-
            {{ .password | toString }}

    data:
    - secretKey: password
      remoteRef:
        key: e6qmgjuu54v6td239geb
        property: password
    - secretKey: username
      remoteRef:
        key: e6qmgjuu54v6td239geb
        property: username
    - secretKey: url
      remoteRef:
        key: e6qmgjuu54v6td239geb
        property: url
