---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: cluster-external-secret-cert
spec:
  externalSecretName: "cert-es"

  namespaceSelector:
    matchLabels:
      momo-secret-cert: yc-auth-cert

  refreshTime: "1m"

  externalSecretSpec:
    secretStoreRef:
      name: cluster-secret-store-cert
      kind: ClusterSecretStore

    refreshInterval: "1h"
    target:
      name: momo-main-cert
      template:
        type: kubernetes.io/tls
    data:
    - secretKey: tls.crt
      remoteRef:
        key: fpq2e83qhudldg0q1jtk
        property: chain
    - secretKey: tls.key
      remoteRef:
        key: fpq2e83qhudldg0q1jtk
        property: privateKey
