---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "cluster-external-secret-cr-lockbox"
spec:

  externalSecretName: "cr-lockbox-es"

  namespaceSelector:
    matchLabels:
      momo-secret-cr-lockbox: yc-auth-lockbox
  refreshTime: "1m"

  externalSecretSpec:
    secretStoreRef:
      name: cluster-secret-store-lockbox
      kind: ClusterSecretStore

    refreshInterval: "1h"

    target:
      name: momo-cr-lockbox
      template:
        # Use inline templates to construct your desired config file that contains your secret
        # no new lines at the end!!!
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: |-
            {{ .dockerconfigjson | toString }}

    data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: e6q61mcma1pf02e9keim
        property: dockerconfigjson
